/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "DVDAC_1.h"
#include "ADC_DelSig_1.h"
#include "Pin_Counter_aliases.h"
#include "Pin_Counter.h"
#include "Pin_Working_aliases.h"
#include "Pin_Working.h"
#include "VDAC8_1.h"
#include "TIA_1.h"
#include "Opamp_1.h"
#include "timer_clock.h"
#include "Timer_1.h"
#include "isr_timer.h"
#include "Pin_DAC_1_aliases.h"
#include "Pin_DAC_1.h"
#include "Pin_Refference_aliases.h"
#include "Pin_Refference.h"
#include "Pin_DAC_2_aliases.h"
#include "Pin_DAC_2.h"
#include "UART.h"
#include "Pin_VirtualGround_aliases.h"
#include "Pin_VirtualGround.h"
#include "DVDAC_1_DMA_dma.h"
#include "DVDAC_1_VDAC8.h"
#include "DVDAC_1_IntClock.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

